### ISSUE TITLE
[cli-installer] syslinux installation is broken (bios)

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools-livecd#13]
Seems syslinux bootloader installation is currently broken. We have to check why that is. I was not able to use it with GPT format. MBR I didn't check yet ...

**Comment by udeved** [comment]
Should we just remove syslinux install option?

**Comment by philmmanjaro** [comment]
If needed, why not.

**Comment by udeved** [comment]
The installer code is pretty huge for scripts.
I am not keen to maintain it, more to fix bugs and possibly cut down code and reuse manjaro-tools code for net install.

**Comment by udeved** [comment]
Btw, can't we do localization with gettext?

**Comment by philmmanjaro** [comment]
I didn't knew about gettext in the past I did the installer. Feel free to do it but keep in mind that calamares gets a cli version also ...

**Comment by udeved** [comment]
Good to know,I wasn't gonna put huge efforts in it. I just noticed, there would be couple of things to fix and address in the code, but oh my, is big.

**Comment by udeved** [comment]
I'll remove syslinx install, should be best solution.

**Comment by philmmanjaro** [comment]
Exactly. Case "closed".

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-cli-installer/commit/ca0955d3bc089977a39def5ae8980061f9567706
