### ISSUE TITLE
[cli installer] serious problem(s)?

### ISSUE THREAD

**Issue by excalibur1234** [manjaro/manjaro-tools-livecd#14]
i had to use the (latest) cli installer recently.
i used my own net-minial: 
https://forum.manjaro.org/index.php?topic=22491.0
https://github.com/excalibur1234/manjaro-tools-iso-profiles/tree/master/net-minimal

i tried to install multiple times (at least 8 times) to an USB3 stick, which was partitioned to 2 ext4 partitions using the cli installer. i used the net-minimal ISO image (64bit), updated it to the latest packages of the unstable branch, or downgraded it the stable branch. i also varied the use german and english (default) keybaord layout. this seemed to make a difference in cli installler behavior:

1. kind of behavior: i noticed a problem during the installation of "set mountpoint of partition": the swap and root partitions were successfully mounted, but the files system could not be mounted to \\install\ (the error message told me something like that).
i could continue with the installation without a problem. but i could not install the bootloader, because the file system was not mounted (another error message - i could not continue afterwards).

2. kind of behavior: i did not notice any errors during the mounting of paritions. then, i began the installation of the system. at the end of the very first part of the installation it told me something like "root image installation successful. net-minimal image installation successful" and offered a "continue" button. but i was unable to press "return" to continue. when i used the arrow keys the message moved. the "tab" key did not move the focus. i could not continue the installation.

3. kind of behavior: exactly as the 2. kind of behavior, but when i pressed "enter" (the key on the numpad) the installation continued without an error. when i rebooted my system, it tried to boot grub. then, grub rescue told me: "isolinux.bin missing or corrupt". i was unable to boot my system.

i am not sure, what the cause of this serious bug is. it could be an ext4 kernel 4.0 bug (https://forum.manjaro.org/index.php?topic=22940.0), a cli installler bug, a bug with my net-minimal manjaro-tools-iso-profile, a bug in grub (only if it got updated recently), or a problem with my hardware. unfortunately, i am not able to do any more tests with this in the near future, because my SSD broke.

i have already reported this bug here: https://forum.manjaro.org/index.php?topic=22491.msg201915#msg201915
it looks like that guy experienced the 2. kind of behavior. so, there seems to be at least one bug in the cli installer.
edit: i just installed the latest manjaro lxqt (64bit) on real hardware using the cli installer and experienced also the 2. kind of behavior. there definitely is a bug in the cli installer!

i have tested my net-minmal image in virtualbox before i uploaded it. this means that there is likely no problem in my net-minimal manjaro-tools-iso-profile.

do you experience any problems when installing with the latest cli installer using kernel 4.0 on real hardware?

**Comment by excalibur1234** [comment]
i have just rebuild the net-minimal image, but with kernel 3.19 and the "stable" branch (this means: without the latest changes to the cli installer).

i experienced the 2. kind of behavior as described in my previous comment/post when i tried to install to real hardware: this time, i installed to a hard drive and NOT a usb3 stick. i managed to use the workaround (play around a little and then press the "enter" key on the numpad to continue).

i did not experience the 3. or 1. kind of behavior.

**Comment by philmmanjaro** [comment]
All kernels are affected due the [kernel bug](https://github.com/manjaro/packages-core/issues/11). CLI-Installer might have also some issues. I've to check that later, when I find some time. We are currently focusing on our graphical installers and might drop the CLI version with 0.8.13. net-minimal might be skipped also ...

**Comment by philmmanjaro** [comment]
@excalibur1234: please test [0.8.12.302-1 (May 25 23:44)](http://sourceforge.net/projects/manjarotest/files/0.8.13/xfce-minimal/0.8.13-dev/) and report back if there are still the same issues ...

**Comment by excalibur1234** [comment]
i have just tested the latest dev image you linked. i used the cli installer (within the xfce DE).
i did not experience any of the above mentioned problems.

maybe i will do some more testing later. in case i find these problems again, i will reopen this issue.

**Comment by excalibur1234** [comment]
i have just build another net-minimal image based on kernel 3.18 and the unstable branch.

i installed it on real hardware the same as i installed it in the first post. i did not encounter any errors.
this really closes this issue!
