### ISSUE TITLE
try to fix uefi bootloader installation

### ISSUE THREAD

**Issue by aadityabagga** [manjaro/manjaro-tools-livecd#16]
remove efistub methods as they seem to be outdated and/or broken (rEFInd method is out of date as reported by a user (change of path and files), and gummiboot has been changed to bootctl and is probably systemd specific now..)

Also removed uefi_i386 bootloader installation as not sure if it is used or works...

Its in pull https://github.com/manjaro/manjaro-tools-livecd/pull/15

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-cli-installer/commit/4af20ceffa16855d885341e1f45f736c68aa1425
