### ISSUE TITLE
sonar desktop items

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-livecd#19]
The sonar part in [live script](https://github.com/manjaro/manjaro-tools-livecd/blob/master/bin/desktop-items.in) can be removed. We are now creating these items also for the installed system and do this from the settings packages:
https://github.com/manjaro/desktop-settings/commit/491bb2fd4c34af403be12ef1f0e07fbacffcaa4f

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools-livecd/commit/609e87f234625482b62ed8847f04d017fa866e79
