### ISSUE TITLE
renaming of sonar launchers not working 

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools-livecd#20]
Just rebuilt sonar-mate and the launchers are not being renamed.
``echo $ID`` returns nothing ...

**Comment by oberon2007** [comment]
Could you please have another look, @udeved ?
I think we need to use something else to determine a sonar ISO. Maybe not too elegant, but what about checking the presence of a package like **sonar-isolinux** or **sonar-{mate,gnome}-settings**? Even **orca** would be an option because it will be present on every sonar ISO and never on a regular manjaro ISO.

**Comment by oberon2007** [comment]
Since it's a bit of a task to build this 1.7G image ... :wink: I'm uploading a test-build to https://sourceforge.net/projects/manjaro-testing/files/sonar/mate-edition/16.06-dev/x86_64/ for everyone who wants to experiment with the current state of sonar-mate.
@philmmanjaro @teo @coffeeking

**Comment by oberon2007** [comment]
https://github.com/manjaro/manjaro-tools-livecd/commit/1bac6d9e356e19b99429e7e9b334b1bef924a2f5 is still not woking, because as I already said: These variables are not returning anything:
```
$ echo $ID
$ echo $NAME
```
nada

**Comment by udeved** [comment]
I built gnome sonar, and there is definitely /etc/os-release present in root-image.

**Comment by oberon2007** [comment]
present in mate aswell. however the variables are not exported obviously
```
[sonar@sonar ~]$ cat /etc/os-release 
NAME="Sonar Linux"
ID=manjaro
PRETTY_NAME="Sonar Linux"
ANSI_COLOR="1;32"
HOME_URL="http://www.sonargnulinux.com/"
SUPPORT_URL="http://www.sonargnulinux.com/"
BUG_REPORT_URL="http://sonargnulinux.com"
```
```
[sonar@sonar ~]$ echo $ID

```

**Comment by udeved** [comment]
Have you looked at the launcher file, or just the link name visible?
The file is sourced, and $NAME set if sonar.
Maybe the condition doesn't evaluate properly.

**Comment by oberon2007** [comment]
Ah. Yes the file is sourced of course, sorry.
But:
```
[sonar@sonar Desktop]$ cat calamares.desktop 
[Desktop Entry]
Name=Install Manjaro Linux (Calamares)
GenericName=Live Installer (Calamares)
Comment=Install the operating system to disk
Exec=sudo /usr/bin/calamares
Icon=calamares
Terminal=False
Type=Application
Categories=System;
```

**Comment by oberon2007** [comment]
In lines 19 and 27 $src needs to be replaced with $xdg !

**Comment by oberon2007** [comment]
apart from that the variables inside the sed commands don't work. It's being replaced with white space.

**Comment by udeved** [comment]
You guys drive me nuts with this silly stuff.
Will have a look.
