### ISSUE TITLE
pacman-mirrors in live session

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-livecd#21]
Shouldn't the pacman-mirrors -m random be moved to pacmann-init service script?

Reason is, on openrc, the randomizing doesn't have net connection yet, when it is run.
Moving it to service would accomplish that.

How is it with systemd? Is net service started before manjaro-live service?

**Comment by Kirek** [comment]
When using -m option pacman-mirrors doesn't use the network at all.

That being said, moving it to it's own services would be okay too.

**Comment by udeved** [comment]
So pacman-mirrors throws a useless message about server init failed?

**Comment by Kirek** [comment]
what message?

**Comment by udeved** [comment]
![msg] (http://s23.postimg.org/c4ep4qjvf/image.png)

**Comment by Kirek** [comment]
Weird, this may be a gtk/xorg error though, when loading the gtk libraries...

**Comment by udeved** [comment]
Hmm, perhaps, coincidence. It started after this was mirrors randomizer was added.

Btw, can you take a look at systemd service for tweaking, depends?

https://github.com/manjaro/manjaro-tools-livecd/commit/44119d3eb8d8526d08c8b34a47bcb647a0734b25

**Comment by Kirek** [comment]
The systemd service should be fine like this.

Yeah, pacman-mirros somehow generates that error, it imports the gtk libraries if they are found in the system, for interactive mode, even if you don't start it with interactive activated.

**Comment by Kirek** [comment]
Confirming this a problem when loading gtk, can reproduce it in a chroot:
>[root@root ~]# pacman-mirrors -m rank -c France
Unable to init server: Could not connect: Connection refused
:: Querying servers, this may take some time...
France
-> 0.207 http://manjarolinux.polymorf.fr/unstable/$repo/$arch
-> 0.236 http://mirror.lignux.com/manjaro/unstable/$repo/$arch
:: Generated and saved '/etc/pacman.d/mirrorlist' mirrorlist.
[root@root ~]# pacman-mirrors -m random
**Unable to init server: Could not connect: Connection refused**
:: Randomizing server list...
:: Generated and saved '/etc/pacman.d/mirrorlist' mirrorlist.

**Comment by Kirek** [comment]
https://github.com/manjaro/pacman-mirrors/commit/67e6d0869b4822c8876c24510da5359fe661653f
