### ISSUE TITLE
Transfer runlevel setting(symlinks) to buildiso

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-livecd#3]
Lets transfer the symlinks for the init packages to manjaro-tools in start_service_live array.
The advantage would be to be able to test say pacman-boot, and to enable/disable a live service without rebuilding the package.

**Comment by udeved** [comment]
Opinions?
Its not strictly needed, but we would configure for example systemd live services with start_systemd_live array.

**Comment by udeved** [comment]
I made it so.
manjaro-tools-0.9.6.2 are required for livecd devel branch.

**Comment by manjaro** [comment]
Ok, fine.
