### ISSUE TITLE
Move livecd and profiles to community repo?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-livecd#4]
Should the pkgbuilds remain in openrc repo?
They are not updated, but Phil updated the repos.
We somehow need to sync them.

**Comment by manjaro** [comment]
If you like move the PKGBUILDs to the needed github repos. All openrc-packages get released to community for now ...

**Comment by udeved** [comment]
I am fine with having a openrc git repo.

I was just wondering if the majaro-tools pkgbuilds should be moved directly to community?
So manjaro-tools, manjaro-livecd and iso-profiles builds.

**Comment by manjaro** [comment]
If needed, I'd rather put them into our extra repository. We can do that when we have our first stable release built with manjaro-tools.
