### ISSUE TITLE
cli-installer.desktop is not executable

### ISSUE THREAD

**Issue by aadityabagga** [manjaro/manjaro-tools-livecd#8]
<a href="http://i.imgur.com/ovlv8SB.png">
  <img src="http://imgur.com/ovlv8SBl.png" />
</a>

One more error:
While booting I get:
~~~~
 * Running mhwd-live script ...
/usr/bin/mhwd-live: line 5: kernel_cmdline: command not found
/usr/bin/mhwd-live: line 6: kernel_cmdline: command not found
~~~~

**Comment by philmmanjaro** [comment]
On XFCE 0.9.0-pre3 I only can reproduce the launcher rights issues but not the one you have with **mwhd-live**

**Comment by philmmanjaro** [comment]
9dc50d5abea8376c9307ebd07c9a13d9f5a51475 should fix the desktop file issues, though.

**Comment by aadityabagga** [comment]
Maybe the second error is openrc specific or has been fixed in unstable/git.

**Comment by philmmanjaro** [comment]
Please also check [a3d1095@manjaro-tools](https://github.com/manjaro/manjaro-tools/commit/a3d1095887ae615986f0d7a536bcb72399487ea1) However the needed line is included in [util-livecd.sh](https://github.com/manjaro/manjaro-tools/blob/devel/lib/util-livecd.sh)

**Comment by philmmanjaro** [comment]
Seems it started with [4a031bc@manjaro-tools](https://github.com/manjaro/manjaro-tools/commit/4a031bc0ceac40d51513f068579d45675edf3464). In short, try with both devel branches.

**Comment by philmmanjaro** [comment]
Maybe this will fix it. [e4cf7bc@manjaro-tools](https://github.com/manjaro/manjaro-tools/commit/e4cf7bcd28e8a255eb970e9526be94b8bb58c58e)

**Comment by philmmanjaro** [comment]
455ec26bdabcdd11e2dc2c524ad4728608db0105 should fix this.

**Comment by philmmanjaro** [comment]
No, **exo-0.10.3-2** should fix the **Failed to execute child process** issue

**Comment by aadityabagga** [comment]
Thx for the help Phil.

**Comment by aadityabagga** [comment]
Hmm, when installing at the Disk preparation step, when formatting the partition, I get an error:

<a href="http://i.imgur.com/iZuAq2g.png">
  <img src="http://imgur.com/iZuAq2gl.png" />
</a>

Same with ext4 also.

**Comment by philmmanjaro** [comment]
I didn't test the cli-installer lately. Have to check.

**Comment by philmmanjaro** [comment]
This issue is closed, regarding desktop file and not been able to execute the installer. Your partitioning issue, please open a new ticket and describe exactly which steps you have done. I just did a quick test with my latest [devbuild](http://sourceforge.net/projects/manjarotest/files/0.9.0/xfce-minimal/0.9.0-dev/) and partitioning module passed in semi-automatic mode for both, msdos and gpt.

**Comment by aadityabagga** [comment]
Right, I will just wait for an updated version of manjaro-tools{-livecd} as it may have been fixed, I dont know since there is no changelog..
