### ISSUE TITLE
Can't push changes?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools-livecd#9]
I can't push fixed to unstable branch to match the buildiso changes

**Comment by philmmanjaro** [comment]
What do you mean by that exactly?

**Comment by udeved** [comment]
I get auth error, no access.

**Comment by philmmanjaro** [comment]
Hmm, post me that error. Did you pull my latest changes into your work dir?

**Comment by udeved** [comment]
Yes, I pulled and tried to push to a new unstable branch.
I am not at home atm, so the error msg has to wait until the evening.

**Comment by philmmanjaro** [comment]
Normally there should be no issue. When I know the error I might be able to help. So lets wait until you're home on that one ;)

**Comment by udeved** [comment]
~~~
$ git push origin unstable
Enter passphrase for key '/home/devtux/.ssh/id_rsa': 
ERROR: Permission to manjaro/manjaro-tools-livecd.git denied to udeved.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
~~~

Access rights ok? Only occurs with this repo.

**Comment by philmmanjaro** [comment]
Was a rights issue. This repo was not assigned to any team, except owners.
